[project]
name = "md-to-html"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleach>=6.3.0",
    "flask>=3.1.2",
    "markdown>=3.10",
    "python-dotenv>=1.2.1",
]
